version: '3'

services:

    ez:
        build:
            context: images/ez
            args:
                debian_mirror: ${TESTSTACK_DEBIAN_MIRROR:-none}
                debian_version: ${TESTSTACK_DEBIAN_VERSION:-buster}
                php_version: ${TESTSTACK_PHP_VERSION:-default}
                timezone: ${TESTSTACK_TZ:-none}
                do_update_os: ${TESTSTACK_UPDATE_OS_ON_BUILD:-true}
        hostname: ez
        container_name: ${TESTSTACK_PROJECT_NAME:-euts}_ez
        environment:
            - CONTAINER_USER_UID=${CONTAINER_USER_UID:-1000}
            - CONTAINER_USER_GID=${CONTAINER_USER_GID:-1000}
            - TESTSTACK_PROJECT_NAME
            - TESTSTACK_SETUP_APP_ON_BOOT
            - DB_TYPE=${DB_TYPE:-mysql}
            - DB_HOST
            - MYSQL_VERSION=${MYSQL_VERSION:-5.6}
            - POSTGRESQL_VERSION=${POSTGRESQL_VERSION:-9.5}
            - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root_test}
            - DB_CHARSET
            - DB_EZ_USER=${DB_EZ_USER:-ezp}
            - DB_EZ_PASSWORD=${DB_EZ_PASSWORD:-ezp}
            - DB_EZ_DATABASE=${DB_EZ_DATABASE:-behattestdb}
            # Configuration for the eZ test env to build
            - EZ_PACKAGES
            - EZ_COMPOSER_LOCK
            - EZ_BUNDLES
            - EZ_LEGACY_EXTENSIONS
            # Name of a symfony config file containing parameters and services used by the tests
            - EZ_TEST_CONFIG_SYMFONY
            # Configuration used by Symfony when running via phpunit
            - APP_ENV=${APP_ENV:-behat}
            - SYMFONY_ENV=${SYMFONY_ENV:-behat}
            # As opposed to TRAVIS=true ;-)
            - DOCKER=true
        volumes:
            - ../:/home/test/teststack
            - ${TESTSTACK_APP_DIR:-../../}:/home/test/bundle
            - ${TESTSTACK_DATA_DIR:-./data}/.composer/:/home/test/.composer

#networks:
#    default:
#        ipam:
#            config:
#                - subnet: "${TESTSTACK_SUBNET:-172.19.30}.0/24"
