version: '3'

services:

    mysql:
        image: ${COMPOSE_PROJECT_NAME:-euts}_mysql
        build:
            context: images/mysql
            args:
                do_update_os: ${TESTSTACK_UPDATE_OS_ON_BUILD:-true}
                db_vendor: ${DB_VENDOR:-mysql}
                # note: Travis Xenial and Bionic images come with mysql 5.7 by default; Focal comes with mysql 8.0
                #       But mysql 5.7 is not recommended for EZP 5.4, so we default to 5.6
                mysql_version: ${MYSQL_VERSION:-5.6}
                project_name: ${COMPOSE_PROJECT_NAME:-euts}
                timezone: ${TESTSTACK_TZ:-none}
        hostname: mysql
        container_name: ${COMPOSE_PROJECT_NAME:-euts}_mysql
        environment:
            - CONTAINER_USER_UID=${CONTAINER_USER_UID:-1000}
            - CONTAINER_USER_GID=${CONTAINER_USER_GID:-1000}
            - DB_TYPE=mysql
            # This is a courtesy - inside the container we should be able to retrieve the installed db version easily...
            - MYSQL_VERSION
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root_test}
            - MYSQL_USER=${DB_EZ_USER:-ezp}
            - MYSQL_PASSWORD=${DB_EZ_PASSWORD:-ezp}
            - MYSQL_DATABASE=${DB_EZ_DATABASE:-behattestdb}
            - EZ_PACKAGES
            # As opposed to TRAVIS=true ;-)
            - DOCKER=true
        volumes:
            #- ./config/mysql/mysql_${TESTSTACK_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ${TESTSTACK_DATA_DIR:-./data}/mysql/:/var/lib/mysql
            - ${TESTSTACK_LOGS_DIR:-./logs}/mysql/:/var/log/mysql
            - ../:/home/test/teststack
        #tmpfs:
        #    # used for mysql temp tables. Useful with ez5 db schema / queries (it creates lots of temp tables on disk)
        #    - /tmpfs:mode=777
        # uncomment this to be able to access the db from the host
        #ports:
        #    - "3307:3306"
        # nb: this prevents the image to start on some ubuntu installs because of apparmor config...
        #privileged: true
