version: '3'

services:

    postgresql:
        image: ${COMPOSE_PROJECT_NAME:-euts}_postgresql
        build:
            context: images/postgresql
            args:
                do_update_os: ${TESTSTACK_UPDATE_OS_ON_BUILD:-true}
                # note: Travis Xenial images come with PG 9.4-9.6,10; Bionic with 9.3-9.6,10,11 and Focal with 12
                #       We go with 9.5 as default because it is the lowest upstream supported version as of 11/2020...
                postgresql_version: ${POSTGRESQL_VERSION:-9.5}
                project_name: ${COMPOSE_PROJECT_NAME:-euts}
                timezone: ${TESTSTACK_TZ:-none}
        hostname: postgresql
        container_name: ${COMPOSE_PROJECT_NAME:-euts}_postgresql
        environment:
            - CONTAINER_USER_UID=${CONTAINER_USER_UID:-1000}
            - CONTAINER_USER_GID=${CONTAINER_USER_GID:-1000}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root_test}
            # As opposed to TRAVIS=true ;-)
            - DOCKER=true
        volumes:
            - ${TESTSTACK_DATA_DIR:-./data}/postgresql/:/var/lib/postgresql
            - ${TESTSTACK_LOGS_DIR:-./logs}/postgresql/:/var/log/postgresql
        # uncomment this to be able to access the db from the host
        #ports:
        #    - "5433:5432"
