# A Travis configuration file for a bundle which aims to be compatible with both eZPublish 5 and eZPlatform

language: php

services:
    # MySQL is required to run the integration tests
    - mysql

env:
    # Env vars which have the same values across the whole test matrix: database configuration and Symfony env to use
    global:
        - SYMFONY_ENV=behat
        - DB_HOST=localhost
        - DB_TYPE=mysql
        - DB_EZ_USER=ezp
        - DB_EZ_PASSWORD=ezp
        - DB_EZ_DATABASE=behattestdb

matrix:
    # A wide test matrix - running tests at least once for each stable PHP version, and across as many different versions
    # as possible of eZPublish / eZPlatform.
    # Besides the bundle under test (Kaliop\eZMigrationBundle\EzMigrationBundle), the tests require, when available for
    # the current eZ kernel, the presence of ezplatform-xmltext-fieldtype, ez-matrix-bundle, tagsbundle, zplatform-matrix-fieldtype.allow_failures:
    # Extra composer packages are required to be installed and extra Symfony Bundles are required to be activated
    # as dependencies, depending on the current eZ kernel, just to be able for the kernel to run.
    include:
        # The last version of eZPublish Community Project, aka eZPublish 5, corresponds to eZPublish Platform (Enterprise) 5.4
        - php: 5.6
          # Composer takes too much time and memory for our dependencies when running on PHP 5.6.
          # So we use a pre-calculated composer.lock file for installing dependencies instead of a list of packages
          # (the lock file is stored within our bundle's source code)
          env: EZ_COMPOSER_LOCK=Tests/composer/composer-cp_2104111.lock EZ_BUNDLES='Kaliop\eZMigrationBundle\EzMigrationBundle EzSystems\MatrixBundle\EzSystemsMatrixBundle Netgen\TagsBundle\NetgenTagsBundle'

        # eZPlatform 1 aka eZPublish 6 - earliest LTS release is 1.7
        # Not compatible with ezplatform-matrix-fieldtype
        - php: 7.0
          env: EZ_PACKAGES='ezsystems/ezplatform:~1.7.9 ezsystems/ezplatform-xmltext-fieldtype:^1.1 ezsystems/ez-matrix-bundle:^0.2.1 netgen/tagsbundle:^2.2 ezsystems/behatbundle:^6.3' EZ_BUNDLES='Kaliop\eZMigrationBundle\EzMigrationBundle EzSystems\EzPlatformXmlTextFieldTypeBundle\EzSystemsEzPlatformXmlTextFieldTypeBundle EzSystems\MatrixBundle\EzSystemsMatrixBundle Netgen\TagsBundle\NetgenTagsBundle'
        # last version available of eZPlatform 1 - also an LTS
        - php: 7.1
          env: EZ_PACKAGES='ezsystems/ezplatform:~1.13.5 ezsystems/ezplatform-xmltext-fieldtype:^1.1 ezsystems/ez-matrix-bundle:^0.2.1 netgen/tagsbundle:^2.2 ezsystems/behatbundle:^6.3' EZ_BUNDLES='Kaliop\eZMigrationBundle\EzMigrationBundle EzSystems\EzPlatformXmlTextFieldTypeBundle\EzSystemsEzPlatformXmlTextFieldTypeBundle EzSystems\MatrixBundle\EzSystemsMatrixBundle Netgen\TagsBundle\NetgenTagsBundle'

        # eZPlatform 2 aka eZPublish 7
        # Comes with ezplatform-matrix-fieldtype included since 2.5
        # sensio/generator-bundle is only needed because we run the tests using 'behat' sf env
        - php: 7.2
          env: EZ_PACKAGES='ezsystems/ezplatform:~2.3.2 ezsystems/ezplatform-xmltext-fieldtype:^1.7 ezsystems/ezplatform-matrix-fieldtype:^1.0 netgen/tagsbundle:^3.2 ezsystems/behatbundle:^6.5 ezsystems/repository-forms:<=2.4 sensio/generator-bundle' EZ_BUNDLES='Kaliop\eZMigrationBundle\EzMigrationBundle EzSystems\EzPlatformXmlTextFieldTypeBundle\EzSystemsEzPlatformXmlTextFieldTypeBundle EzSystems\EzPlatformMatrixFieldtypeBundle\EzPlatformMatrixFieldtypeBundle EzSystems\EzPlatformGraphQL\EzSystemsEzPlatformGraphQLBundle Netgen\TagsBundle\NetgenTagsBundle Lolautruche\EzCoreExtraBundle\EzCoreExtraBundle'
        # next-to-latest version currently available of eZPlatform 2
        - php: 7.3
          env: EZ_PACKAGES='ezsystems/ezplatform:~2.4.2 ezsystems/ezplatform-xmltext-fieldtype:^1.8 ezsystems/ezplatform-matrix-fieldtype:^1.0 netgen/tagsbundle:^3.3 ezsystems/behatbundle:^6.5 sensio/generator-bundle' EZ_BUNDLES='Kaliop\eZMigrationBundle\EzMigrationBundle EzSystems\EzPlatformXmlTextFieldTypeBundle\EzSystemsEzPlatformXmlTextFieldTypeBundle EzSystems\EzPlatformMatrixFieldtypeBundle\EzPlatformMatrixFieldtypeBundle EzSystems\EzPlatformGraphQL\EzSystemsEzPlatformGraphQLBundle Netgen\TagsBundle\NetgenTagsBundle Lolautruche\EzCoreExtraBundle\EzCoreExtraBundle'
        # latest version currently available of eZPlatform 2 - currently 2.5, which is an LTS
        - php: 7.4
          env: EZ_PACKAGES='ezsystems/ezplatform:^2.5.15 ezsystems/ezplatform-xmltext-fieldtype:^1.9 netgen/tagsbundle:^3.4 ezsystems/behatbundle:^7.0 sensio/generator-bundle overblog/graphiql-bundle' EZ_BUNDLES='Kaliop\eZMigrationBundle\EzMigrationBundle EzSystems\EzPlatformXmlTextFieldTypeBundle\EzSystemsEzPlatformXmlTextFieldTypeBundle Netgen\TagsBundle\NetgenTagsBundle Lolautruche\EzCoreExtraBundle\EzCoreExtraBundle' CODE_COVERAGE=1

before_install:
    # zip and unzip are used by composer
    - sudo apt-get install -y zip unzip

install:
    # Retrieve the TestStack tool
    - git clone --depth 1 --branch 0.1.0 git@github.com:tanoconsulting/euts.git teststack
    # Fix perms on shell scripts, just in case...
    - chmod 755 ./teststack/bin/*.sh  ./teststack/bin/setup/*.sh
    # Run the TestStack tool setup script. This runs Composer, sets up an appropriate php and eZ configuration and creates a db schema with default data.
    # We wrap script execution in a `travis_wait` call as sometimes this takes a fair amount of time...
    - travis_wait 30 ./teststack/bin/setup.sh

script:
    # Simply run your tests the same way you would do without the Test Stack
    # Assuming tests reside in the Tests folder and are executed with phpunit:
    - php vendor/phpunit/phpunit/phpunit --stderr --colors Tests
