name: CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.operating-system }}
        env:
            SYMFONY_ENV: behat
            DB_HOST: localhost
            # @todo run one test on pgsql
            DB_TYPE: mysql
            DB_ROOT_PASSWORD: root
            DB_EZ_USER: ezp
            DB_EZ_PASSWORD: ezp
            DB_EZ_DATABASE: behattestdb
            PHP_VERSION: ${{ matrix.php }}
        strategy:
            fail-fast: false
            matrix:
                # @see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners for available os versions
                # @todo add some tests running on 'windows-latest'
                include:
                    - php: "5.6"
                      operating-system: 'ubuntu-18.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.cp.env'
                    - php: "7.0"
                      operating-system: 'ubuntu-18.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.1.7.env'
                    - php: "7.1"
                      operating-system: 'ubuntu-18.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.1.13.env'
                    - php: "7.2"
                      operating-system: 'ubuntu-20.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.2.3.env'
                    - php: "7.3"
                      operating-system: 'ubuntu-20.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.2.4.env'
                    - php: "7.4"
                      operating-system: 'ubuntu-20.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.2.5.env'
                    #- php: "8.0"
                    #  operating-system: 'ubuntu-22.04'
                    #  config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.3.2.env'
                    #- php: "8.1"
                    #  operating-system: 'ubuntu-22.04'
                    #  config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.3.2.env'
        steps:
            - uses: actions/checkout@v2

            - run: |
                # just in case...
                chmod 755 ./teststack ./bin/*.sh ./bin/setup/*.sh
                # a minimal composer.json is required to allow installation of package dependencies using "dev-master",
                # fix behattestdb for ez cp version, etc...
                mkdir /tmp/composer_cache
                cp tests/config/composer.json .
                # patch the configuration file we will use: we won't have the mig bundle available
                sed -i 's/Kaliop\\eZMigrationBundle\\EzMigrationBundle //' ${{ matrix.config_file }}

            # set up the test stack locally, ie. without docker containers
            # NB: the php version in use here is not the one from the .env config file, but the one set in the matrix above
            - run: |
                set -a && . ${{ matrix.config_file }} && set +a
                ./bin/setup.sh
                ./bin/sfconsole.sh list

            # reset the env which we built
            - run: 'mv vendor vendor_nodocker'

            # build the test stack docker images - without app setup
            - run: './teststack -e ${{ matrix.config_file }} -n -w 300 build'

            # troubleshooting failures
            #-
            #    if: ${{ failure() }}
            #    run: './teststack -e ${{ matrix.config_file }} logs ez; ./teststack -e ${{ matrix.config_file }} top'

            - run: './teststack -e ${{ matrix.config_file }} logs'

            - run: './teststack -e ${{ matrix.config_file }} ps'

            - run: './teststack -e ${{ matrix.config_file }} services'

            - run: './teststack -e ${{ matrix.config_file }} images'

            - run: './teststack -e ${{ matrix.config_file }} top'

            # @todo using the composer.lock file and vendors from the previous run makes install quicker, but then we
            # should make sure php versions (and extensions) are in sync.
            - run: './teststack -e ${{ matrix.config_file }} exec cp /home/test/teststack/tests/config/composer.json /home/test/bundle'

            - run: './teststack -e ${{ matrix.config_file }} stop'

            - run: './teststack -e ${{ matrix.config_file }} -w 900 setup'

            # @todo run more commands...
            #- run: './teststack -e ${{ matrix.config_file }} resetdb'

            - run: './teststack -e ${{ matrix.config_file }} exec ../teststack/bin/sfconsole.sh list'

            - run: './teststack -e ${{ matrix.config_file }} cleanup ez-logs'

            - run: './teststack -e ${{ matrix.config_file }} stop'

            - run: './teststack -e ${{ matrix.config_file }} cleanup logs'

            # troubleshooting failures
            #-
            #    if: ${{ failure() }}
            #    run: |
            #        env
            #        php -i
            #        docker logs
