name: CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.operating-system }}
        env:
            SYMFONY_ENV: behat
            DB_HOST: localhost
            # nb: the db type is used as flag to decide between local and docker tests
            DB_TYPE: ${{ matrix.php }}
            DB_ROOT_PASSWORD: root
            DB_EZ_USER: ezp
            DB_EZ_PASSWORD: ezp
            DB_EZ_DATABASE: behattestdb
            # @todo
            #PHP_VERSION: ${{ matrix.php }}
        strategy:
            fail-fast: false
            matrix:
                # @see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners for available os versions
                # @todo add some tests running on 'windows-latest'
                # @todo run at least one test on pgsql
                include:
                    - php: "5.6"
                      db: localhost
                      operating-system: 'ubuntu-18.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.cp.env'
                    - php: "7.0"
                      db: localhost
                      operating-system: 'ubuntu-18.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.1.7.env'
                    - php: "7.1"
                      db: localhost
                      operating-system: 'ubuntu-18.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.1.13.env'
                    - php: "7.2"
                      db: localhost
                      operating-system: 'ubuntu-20.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.2.3.env'
                    - php: "7.3"
                      db: localhost
                      operating-system: 'ubuntu-20.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.2.4.env'
                    - php: "7.4"
                      db: localhost
                      operating-system: 'ubuntu-22.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.2.5.env'
                    #- php: "8.0"
                    #  db: localhost
                    #  operating-system: 'ubuntu-22.04'
                    #  config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.3.2.env'
                    #- php: "8.1"
                    #  db: localhost
                    #  operating-system: 'ubuntu-22.04'
                    #  config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.3.2.env'

                    - php: "5.6"
                      db: mysql
                      operating-system: 'ubuntu-18.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.cp.env'
                    - php: "7.0"
                      db: mysql
                      operating-system: 'ubuntu-18.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.1.7.env'
                    - php: "7.1"
                      db: mysql
                      operating-system: 'ubuntu-18.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.1.13.env'
                    - php: "7.2"
                      db: mysql
                      operating-system: 'ubuntu-20.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.2.3.env'
                    - php: "7.3"
                      db: mysql
                      operating-system: 'ubuntu-20.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.2.4.env'
                    - php: "7.4"
                      db: mysql
                      operating-system: 'ubuntu-22.04'
                      config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.2.5.env'
                    #- php: "8.0"
                    #  db: mysql
                    #  operating-system: 'ubuntu-22.04'
                    #  config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.3.2.env'
                    #- php: "8.1"
                    #  db: mysql
                    #  operating-system: 'ubuntu-22.04'
                    #  config_file: 'doc/config_examples/bundle_with_extra_dependencies/.euts.3.2.env'
        steps:
            - uses: actions/checkout@v2

            - run: |
                # just in case...
                chmod 755 ./teststack ./bin/*.sh ./bin/setup/*.sh
                # a minimal composer.json is required to allow installation of package dependencies using "dev-master",
                # fix behattestdb for ez cp version, etc...
                mkdir /tmp/composer_cache
                cp tests/config/composer.json .
                # patch the configuration file we will use: we won't have the mig bundle available
                sed -i 's/Kaliop\\eZMigrationBundle\\EzMigrationBundle //' ${{ matrix.config_file }}

            # Test: set up the app and check that the sf console works - locally

            # set up the test stack locally, ie. without docker containers
            - if: ${{ matrix.db == localhost }}
              run: |
                set -a && . ${{ matrix.config_file }} && set +a
                ./bin/setup.sh
                ./bin/sfconsole.sh list

            # 2nd test: set up the container stack and check that the sf console works in it

            # @todo stop services such as db, webserver, to leave ore ram available for the docker tests

            # build the test stack docker images - without app setup
            - if: ${{ matrix.db != localhost }}
              run: './teststack -e ${{ matrix.config_file }} -n -w 300 build'

            # troubleshooting failures
            #-
            #    if: ${{ matrix.db != localhost && failure() }}
            #    run: './teststack -e ${{ matrix.config_file }} logs ez; ./teststack -e ${{ matrix.config_file }} top'

            - if: ${{ matrix.db != localhost }}
              run: |
                export TESTSTACK_CONFIG_FILE=${{ matrix.config_file }}
                ./teststack logs
                ./teststack ps
                ./teststack services
                ./teststack images
                ./teststack top
                #./teststack exec cp /home/test/teststack/tests/config/composer.json /home/test/bundle
                ./teststack exec pwd
                ./teststack stop
                # set up the application
                ./teststack setup
                # @todo run more commands...
                #./teststack pause
                #./teststack unpause
                #./teststack resetdb
                ./teststack exec ../teststack/bin/sfconsole.sh list
                ./teststack cleanup ez-logs
                ./teststack stop
                ./teststack cleanup logs

            # troubleshooting failures
            #-
            #    if: ${{ matrix.db != localhost && failure() }}
            #    run: |
            #        env
            #        php -i
            #        docker logs
